Please consider usage await/async
I am proposing a fix for usage with await/async. Running your sample code on Node v7.8.0 would result in : 
const { filename, image } = await download.image(options)
                                    ^^^^^^^^
SyntaxError: Unexpected identifier.
As far as I know, this is because you can't call 'await' outside of an async function. NodeJS REPL doesn't allow you to do that.